# Generated by Django 3.1 on 2021-09-11 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Text_count',
        ),
    ]
